// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.23.4
// source: proto/fileservice.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ImageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileData      []byte                 `protobuf:"bytes,1,opt,name=file_data,json=fileData,proto3" json:"file_data,omitempty"`
	MimeType      string                 `protobuf:"bytes,2,opt,name=mime_type,json=mimeType,proto3" json:"mime_type,omitempty"`
	Quality       int32                  `protobuf:"varint,3,opt,name=quality,proto3" json:"quality,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImageRequest) Reset() {
	*x = ImageRequest{}
	mi := &file_proto_fileservice_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImageRequest) ProtoMessage() {}

func (x *ImageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_fileservice_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImageRequest.ProtoReflect.Descriptor instead.
func (*ImageRequest) Descriptor() ([]byte, []int) {
	return file_proto_fileservice_proto_rawDescGZIP(), []int{0}
}

func (x *ImageRequest) GetFileData() []byte {
	if x != nil {
		return x.FileData
	}
	return nil
}

func (x *ImageRequest) GetMimeType() string {
	if x != nil {
		return x.MimeType
	}
	return ""
}

func (x *ImageRequest) GetQuality() int32 {
	if x != nil {
		return x.Quality
	}
	return 0
}

type ImageResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	CompressedData   []byte                 `protobuf:"bytes,1,opt,name=compressed_data,json=compressedData,proto3" json:"compressed_data,omitempty"`
	Status           string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	ErrorMessage     string                 `protobuf:"bytes,3,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	OriginalSize     int64                  `protobuf:"varint,4,opt,name=original_size,json=originalSize,proto3" json:"original_size,omitempty"`
	CompressedSize   int64                  `protobuf:"varint,5,opt,name=compressed_size,json=compressedSize,proto3" json:"compressed_size,omitempty"`
	CompressionRatio float32                `protobuf:"fixed32,6,opt,name=compression_ratio,json=compressionRatio,proto3" json:"compression_ratio,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ImageResponse) Reset() {
	*x = ImageResponse{}
	mi := &file_proto_fileservice_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImageResponse) ProtoMessage() {}

func (x *ImageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_fileservice_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImageResponse.ProtoReflect.Descriptor instead.
func (*ImageResponse) Descriptor() ([]byte, []int) {
	return file_proto_fileservice_proto_rawDescGZIP(), []int{1}
}

func (x *ImageResponse) GetCompressedData() []byte {
	if x != nil {
		return x.CompressedData
	}
	return nil
}

func (x *ImageResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ImageResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *ImageResponse) GetOriginalSize() int64 {
	if x != nil {
		return x.OriginalSize
	}
	return 0
}

func (x *ImageResponse) GetCompressedSize() int64 {
	if x != nil {
		return x.CompressedSize
	}
	return 0
}

func (x *ImageResponse) GetCompressionRatio() float32 {
	if x != nil {
		return x.CompressionRatio
	}
	return 0
}

type PDFRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	FileData        []byte                 `protobuf:"bytes,1,opt,name=file_data,json=fileData,proto3" json:"file_data,omitempty"`
	Operation       string                 `protobuf:"bytes,2,opt,name=operation,proto3" json:"operation,omitempty"`
	PreserveQuality bool                   `protobuf:"varint,3,opt,name=preserve_quality,json=preserveQuality,proto3" json:"preserve_quality,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *PDFRequest) Reset() {
	*x = PDFRequest{}
	mi := &file_proto_fileservice_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PDFRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PDFRequest) ProtoMessage() {}

func (x *PDFRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_fileservice_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PDFRequest.ProtoReflect.Descriptor instead.
func (*PDFRequest) Descriptor() ([]byte, []int) {
	return file_proto_fileservice_proto_rawDescGZIP(), []int{2}
}

func (x *PDFRequest) GetFileData() []byte {
	if x != nil {
		return x.FileData
	}
	return nil
}

func (x *PDFRequest) GetOperation() string {
	if x != nil {
		return x.Operation
	}
	return ""
}

func (x *PDFRequest) GetPreserveQuality() bool {
	if x != nil {
		return x.PreserveQuality
	}
	return false
}

type PDFResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ProcessedData    []byte                 `protobuf:"bytes,1,opt,name=processed_data,json=processedData,proto3" json:"processed_data,omitempty"`
	Status           string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	ErrorMessage     string                 `protobuf:"bytes,3,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	OriginalSize     int64                  `protobuf:"varint,4,opt,name=original_size,json=originalSize,proto3" json:"original_size,omitempty"`
	CompressedSize   int64                  `protobuf:"varint,5,opt,name=compressed_size,json=compressedSize,proto3" json:"compressed_size,omitempty"`
	CompressionRatio float32                `protobuf:"fixed32,6,opt,name=compression_ratio,json=compressionRatio,proto3" json:"compression_ratio,omitempty"`
	WasCorrupted     bool                   `protobuf:"varint,7,opt,name=was_corrupted,json=wasCorrupted,proto3" json:"was_corrupted,omitempty"`
	WasRepaired      bool                   `protobuf:"varint,8,opt,name=was_repaired,json=wasRepaired,proto3" json:"was_repaired,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *PDFResponse) Reset() {
	*x = PDFResponse{}
	mi := &file_proto_fileservice_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PDFResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PDFResponse) ProtoMessage() {}

func (x *PDFResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_fileservice_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PDFResponse.ProtoReflect.Descriptor instead.
func (*PDFResponse) Descriptor() ([]byte, []int) {
	return file_proto_fileservice_proto_rawDescGZIP(), []int{3}
}

func (x *PDFResponse) GetProcessedData() []byte {
	if x != nil {
		return x.ProcessedData
	}
	return nil
}

func (x *PDFResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *PDFResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *PDFResponse) GetOriginalSize() int64 {
	if x != nil {
		return x.OriginalSize
	}
	return 0
}

func (x *PDFResponse) GetCompressedSize() int64 {
	if x != nil {
		return x.CompressedSize
	}
	return 0
}

func (x *PDFResponse) GetCompressionRatio() float32 {
	if x != nil {
		return x.CompressionRatio
	}
	return 0
}

func (x *PDFResponse) GetWasCorrupted() bool {
	if x != nil {
		return x.WasCorrupted
	}
	return false
}

func (x *PDFResponse) GetWasRepaired() bool {
	if x != nil {
		return x.WasRepaired
	}
	return false
}

type FileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileData      []byte                 `protobuf:"bytes,1,opt,name=file_data,json=fileData,proto3" json:"file_data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileRequest) Reset() {
	*x = FileRequest{}
	mi := &file_proto_fileservice_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileRequest) ProtoMessage() {}

func (x *FileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_fileservice_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileRequest.ProtoReflect.Descriptor instead.
func (*FileRequest) Descriptor() ([]byte, []int) {
	return file_proto_fileservice_proto_rawDescGZIP(), []int{4}
}

func (x *FileRequest) GetFileData() []byte {
	if x != nil {
		return x.FileData
	}
	return nil
}

type FileStats struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OriginalSize  int64                  `protobuf:"varint,1,opt,name=original_size,json=originalSize,proto3" json:"original_size,omitempty"`
	PageCount     int32                  `protobuf:"varint,2,opt,name=page_count,json=pageCount,proto3" json:"page_count,omitempty"`
	FileType      string                 `protobuf:"bytes,3,opt,name=file_type,json=fileType,proto3" json:"file_type,omitempty"`
	IsValid       bool                   `protobuf:"varint,4,opt,name=is_valid,json=isValid,proto3" json:"is_valid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileStats) Reset() {
	*x = FileStats{}
	mi := &file_proto_fileservice_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileStats) ProtoMessage() {}

func (x *FileStats) ProtoReflect() protoreflect.Message {
	mi := &file_proto_fileservice_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileStats.ProtoReflect.Descriptor instead.
func (*FileStats) Descriptor() ([]byte, []int) {
	return file_proto_fileservice_proto_rawDescGZIP(), []int{5}
}

func (x *FileStats) GetOriginalSize() int64 {
	if x != nil {
		return x.OriginalSize
	}
	return 0
}

func (x *FileStats) GetPageCount() int32 {
	if x != nil {
		return x.PageCount
	}
	return 0
}

func (x *FileStats) GetFileType() string {
	if x != nil {
		return x.FileType
	}
	return ""
}

func (x *FileStats) GetIsValid() bool {
	if x != nil {
		return x.IsValid
	}
	return false
}

var File_proto_fileservice_proto protoreflect.FileDescriptor

const file_proto_fileservice_proto_rawDesc = "" +
	"\n" +
	"\x17proto/fileservice.proto\x12\vfileservice\"b\n" +
	"\fImageRequest\x12\x1b\n" +
	"\tfile_data\x18\x01 \x01(\fR\bfileData\x12\x1b\n" +
	"\tmime_type\x18\x02 \x01(\tR\bmimeType\x12\x18\n" +
	"\aquality\x18\x03 \x01(\x05R\aquality\"\xf0\x01\n" +
	"\rImageResponse\x12'\n" +
	"\x0fcompressed_data\x18\x01 \x01(\fR\x0ecompressedData\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12#\n" +
	"\rerror_message\x18\x03 \x01(\tR\ferrorMessage\x12#\n" +
	"\roriginal_size\x18\x04 \x01(\x03R\foriginalSize\x12'\n" +
	"\x0fcompressed_size\x18\x05 \x01(\x03R\x0ecompressedSize\x12+\n" +
	"\x11compression_ratio\x18\x06 \x01(\x02R\x10compressionRatio\"r\n" +
	"\n" +
	"PDFRequest\x12\x1b\n" +
	"\tfile_data\x18\x01 \x01(\fR\bfileData\x12\x1c\n" +
	"\toperation\x18\x02 \x01(\tR\toperation\x12)\n" +
	"\x10preserve_quality\x18\x03 \x01(\bR\x0fpreserveQuality\"\xb4\x02\n" +
	"\vPDFResponse\x12%\n" +
	"\x0eprocessed_data\x18\x01 \x01(\fR\rprocessedData\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12#\n" +
	"\rerror_message\x18\x03 \x01(\tR\ferrorMessage\x12#\n" +
	"\roriginal_size\x18\x04 \x01(\x03R\foriginalSize\x12'\n" +
	"\x0fcompressed_size\x18\x05 \x01(\x03R\x0ecompressedSize\x12+\n" +
	"\x11compression_ratio\x18\x06 \x01(\x02R\x10compressionRatio\x12#\n" +
	"\rwas_corrupted\x18\a \x01(\bR\fwasCorrupted\x12!\n" +
	"\fwas_repaired\x18\b \x01(\bR\vwasRepaired\"*\n" +
	"\vFileRequest\x12\x1b\n" +
	"\tfile_data\x18\x01 \x01(\fR\bfileData\"\x87\x01\n" +
	"\tFileStats\x12#\n" +
	"\roriginal_size\x18\x01 \x01(\x03R\foriginalSize\x12\x1d\n" +
	"\n" +
	"page_count\x18\x02 \x01(\x05R\tpageCount\x12\x1b\n" +
	"\tfile_type\x18\x03 \x01(\tR\bfileType\x12\x19\n" +
	"\bis_valid\x18\x04 \x01(\bR\aisValid2\x99\x02\n" +
	"\vFileService\x12F\n" +
	"\rCompressImage\x12\x19.fileservice.ImageRequest\x1a\x1a.fileservice.ImageResponse\x12@\n" +
	"\vCompressPDF\x12\x17.fileservice.PDFRequest\x1a\x18.fileservice.PDFResponse\x12>\n" +
	"\tRepairPDF\x12\x17.fileservice.PDFRequest\x1a\x18.fileservice.PDFResponse\x12@\n" +
	"\fGetFileStats\x12\x18.fileservice.FileRequest\x1a\x16.fileservice.FileStatsB\x14Z\x12file-service/protob\x06proto3"

var (
	file_proto_fileservice_proto_rawDescOnce sync.Once
	file_proto_fileservice_proto_rawDescData []byte
)

func file_proto_fileservice_proto_rawDescGZIP() []byte {
	file_proto_fileservice_proto_rawDescOnce.Do(func() {
		file_proto_fileservice_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_fileservice_proto_rawDesc), len(file_proto_fileservice_proto_rawDesc)))
	})
	return file_proto_fileservice_proto_rawDescData
}

var file_proto_fileservice_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_proto_fileservice_proto_goTypes = []any{
	(*ImageRequest)(nil),  // 0: fileservice.ImageRequest
	(*ImageResponse)(nil), // 1: fileservice.ImageResponse
	(*PDFRequest)(nil),    // 2: fileservice.PDFRequest
	(*PDFResponse)(nil),   // 3: fileservice.PDFResponse
	(*FileRequest)(nil),   // 4: fileservice.FileRequest
	(*FileStats)(nil),     // 5: fileservice.FileStats
}
var file_proto_fileservice_proto_depIdxs = []int32{
	0, // 0: fileservice.FileService.CompressImage:input_type -> fileservice.ImageRequest
	2, // 1: fileservice.FileService.CompressPDF:input_type -> fileservice.PDFRequest
	2, // 2: fileservice.FileService.RepairPDF:input_type -> fileservice.PDFRequest
	4, // 3: fileservice.FileService.GetFileStats:input_type -> fileservice.FileRequest
	1, // 4: fileservice.FileService.CompressImage:output_type -> fileservice.ImageResponse
	3, // 5: fileservice.FileService.CompressPDF:output_type -> fileservice.PDFResponse
	3, // 6: fileservice.FileService.RepairPDF:output_type -> fileservice.PDFResponse
	5, // 7: fileservice.FileService.GetFileStats:output_type -> fileservice.FileStats
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_fileservice_proto_init() }
func file_proto_fileservice_proto_init() {
	if File_proto_fileservice_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_fileservice_proto_rawDesc), len(file_proto_fileservice_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_fileservice_proto_goTypes,
		DependencyIndexes: file_proto_fileservice_proto_depIdxs,
		MessageInfos:      file_proto_fileservice_proto_msgTypes,
	}.Build()
	File_proto_fileservice_proto = out.File
	file_proto_fileservice_proto_goTypes = nil
	file_proto_fileservice_proto_depIdxs = nil
}
