// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v4.23.4
// source: proto/fileservice.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	FileService_CompressImage_FullMethodName = "/fileservice.FileService/CompressImage"
	FileService_CompressPDF_FullMethodName   = "/fileservice.FileService/CompressPDF"
	FileService_RepairPDF_FullMethodName     = "/fileservice.FileService/RepairPDF"
	FileService_GetFileStats_FullMethodName  = "/fileservice.FileService/GetFileStats"
)

// FileServiceClient is the client API for FileService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FileServiceClient interface {
	CompressImage(ctx context.Context, in *ImageRequest, opts ...grpc.CallOption) (*ImageResponse, error)
	CompressPDF(ctx context.Context, in *PDFRequest, opts ...grpc.CallOption) (*PDFResponse, error)
	RepairPDF(ctx context.Context, in *PDFRequest, opts ...grpc.CallOption) (*PDFResponse, error)
	GetFileStats(ctx context.Context, in *FileRequest, opts ...grpc.CallOption) (*FileStats, error)
}

type fileServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewFileServiceClient(cc grpc.ClientConnInterface) FileServiceClient {
	return &fileServiceClient{cc}
}

func (c *fileServiceClient) CompressImage(ctx context.Context, in *ImageRequest, opts ...grpc.CallOption) (*ImageResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ImageResponse)
	err := c.cc.Invoke(ctx, FileService_CompressImage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fileServiceClient) CompressPDF(ctx context.Context, in *PDFRequest, opts ...grpc.CallOption) (*PDFResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PDFResponse)
	err := c.cc.Invoke(ctx, FileService_CompressPDF_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fileServiceClient) RepairPDF(ctx context.Context, in *PDFRequest, opts ...grpc.CallOption) (*PDFResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PDFResponse)
	err := c.cc.Invoke(ctx, FileService_RepairPDF_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fileServiceClient) GetFileStats(ctx context.Context, in *FileRequest, opts ...grpc.CallOption) (*FileStats, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FileStats)
	err := c.cc.Invoke(ctx, FileService_GetFileStats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FileServiceServer is the server API for FileService service.
// All implementations must embed UnimplementedFileServiceServer
// for forward compatibility.
type FileServiceServer interface {
	CompressImage(context.Context, *ImageRequest) (*ImageResponse, error)
	CompressPDF(context.Context, *PDFRequest) (*PDFResponse, error)
	RepairPDF(context.Context, *PDFRequest) (*PDFResponse, error)
	GetFileStats(context.Context, *FileRequest) (*FileStats, error)
	mustEmbedUnimplementedFileServiceServer()
}

// UnimplementedFileServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedFileServiceServer struct{}

func (UnimplementedFileServiceServer) CompressImage(context.Context, *ImageRequest) (*ImageResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CompressImage not implemented")
}
func (UnimplementedFileServiceServer) CompressPDF(context.Context, *PDFRequest) (*PDFResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CompressPDF not implemented")
}
func (UnimplementedFileServiceServer) RepairPDF(context.Context, *PDFRequest) (*PDFResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RepairPDF not implemented")
}
func (UnimplementedFileServiceServer) GetFileStats(context.Context, *FileRequest) (*FileStats, error) {
	return nil, status.Error(codes.Unimplemented, "method GetFileStats not implemented")
}
func (UnimplementedFileServiceServer) mustEmbedUnimplementedFileServiceServer() {}
func (UnimplementedFileServiceServer) testEmbeddedByValue()                     {}

// UnsafeFileServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FileServiceServer will
// result in compilation errors.
type UnsafeFileServiceServer interface {
	mustEmbedUnimplementedFileServiceServer()
}

func RegisterFileServiceServer(s grpc.ServiceRegistrar, srv FileServiceServer) {
	// If the following call panics, it indicates UnimplementedFileServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&FileService_ServiceDesc, srv)
}

func _FileService_CompressImage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ImageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FileServiceServer).CompressImage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FileService_CompressImage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FileServiceServer).CompressImage(ctx, req.(*ImageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FileService_CompressPDF_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PDFRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FileServiceServer).CompressPDF(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FileService_CompressPDF_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FileServiceServer).CompressPDF(ctx, req.(*PDFRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FileService_RepairPDF_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PDFRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FileServiceServer).RepairPDF(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FileService_RepairPDF_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FileServiceServer).RepairPDF(ctx, req.(*PDFRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FileService_GetFileStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FileServiceServer).GetFileStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FileService_GetFileStats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FileServiceServer).GetFileStats(ctx, req.(*FileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// FileService_ServiceDesc is the grpc.ServiceDesc for FileService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FileService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "fileservice.FileService",
	HandlerType: (*FileServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CompressImage",
			Handler:    _FileService_CompressImage_Handler,
		},
		{
			MethodName: "CompressPDF",
			Handler:    _FileService_CompressPDF_Handler,
		},
		{
			MethodName: "RepairPDF",
			Handler:    _FileService_RepairPDF_Handler,
		},
		{
			MethodName: "GetFileStats",
			Handler:    _FileService_GetFileStats_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/fileservice.proto",
}
